// Logo concepts, round 1 (9 Oct 2026). Generated by tools/build_logos.py.
window.VARIANTS = {
  "projectName": "userandproduct, round 1:",
  "brandName": "userandproduct",
  "concepts": [
    {
      "name": "A. Wordmark (Pure wordmark)",
      "variants": [
        {
          "id": "A",
          "name": "Mark / favicon (lockups: index.html)",
          "description": "Pure wordmark. The name is the logo: userandproduct as one heavy lowercase word, with \"and\" in a light weight and the accent so it reads user / and / product at a glance. Favicon: UP in black weight over an accent rule. Accent: Ink blue.",
          "light": "a-wordmark-icon.svg",
          "dark": "a-wordmark-icon-dark.svg"
        }
      ]
    },
    {
      "name": "B. UP monogram (Monogram)",
      "variants": [
        {
          "id": "B",
          "name": "Mark / favicon (lockups: index.html)",
          "description": "Monogram. U and P share one stem: the user's right side is the product's spine. It also reads \"up\", the direction the site wants to move a career. Favicon: the monogram alone, heavy enough for 16px. Accent: Ink blue.",
          "light": "b-monogram-icon.svg",
          "dark": "b-monogram-icon-dark.svg"
        }
      ]
    },
    {
      "name": "C. Where they meet (Symbolic mark)",
      "variants": [
        {
          "id": "C",
          "name": "Mark / favicon (lockups: index.html)",
          "description": "Symbolic mark. A circle (the person) and a square (the thing they use) are cut out of a solid block; the only filled part between them is the overlap, which is what the site writes about. Favicon: the tile alone. Accent: Ink blue.",
          "light": "c-overlap-icon.svg",
          "dark": "c-overlap-icon-dark.svg"
        }
      ]
    },
    {
      "name": "D. Imprint (Abstract geometric)",
      "variants": [
        {
          "id": "D",
          "name": "Mark / favicon (lockups: index.html)",
          "description": "Abstract geometric. A solid block (the product) with one cut: a head on a body, which is also a P and a doorway into the box. Red block like a publisher's imprint or a seal. Favicon: the red block alone. Accent: Masthead red.",
          "light": "d-imprint-icon.svg",
          "dark": "d-imprint-icon-dark.svg"
        }
      ]
    },
    {
      "name": "E. Cradle (Letterform and metaphor)",
      "variants": [
        {
          "id": "E",
          "name": "Mark / favicon (lockups: index.html)",
          "description": "Letterform and metaphor. A heavy U (the user) holds a rounded square (the product): the product only matters in the hands of the person using it. Favicon: the U and the box. Accent: Ink blue.",
          "light": "e-cradle-icon.svg",
          "dark": "e-cradle-icon-dark.svg"
        }
      ]
    },
    {
      "name": "F. Masthead (Editorial masthead)",
      "variants": [
        {
          "id": "F",
          "name": "Mark / favicon (lockups: index.html)",
          "description": "Editorial masthead. USER / AND / PRODUCT set as one justified block, the way a magazine carries its name on the cover: heavy, square, impossible to mistake for a blog. Favicon: U over P knocked out of a block, red rule between. Accent: Masthead red.",
          "light": "f-masthead-icon.svg",
          "dark": "f-masthead-icon-dark.svg"
        }
      ]
    },
    {
      "name": "G. Pilcrow (Own idea: the paragraph mark)",
      "variants": [
        {
          "id": "G",
          "name": "Mark / favicon (lockups: index.html)",
          "description": "Own idea: the paragraph mark. The pilcrow is the editor's mark for \"a new idea starts here\": two stems (user and product) carried by one bowl (the thinking), in editor's red. It is also a P. Favicon: the pilcrow alone. Accent: Masthead red.",
          "light": "g-pilcrow-icon.svg",
          "dark": "g-pilcrow-icon-dark.svg"
        }
      ]
    },
    {
      "name": "H. Et (Typography history)",
      "variants": [
        {
          "id": "H",
          "name": "Mark / favicon (lockups: index.html)",
          "description": "Typography history. The ampersand began as a scribe's ligature of \"et\", Latin for \"and\". Here the e's bar runs on as the t's crossbar, and the t is in rubric red, the scribe's colour for what matters. Favicon: the et ligature alone. Accent: Masthead red.",
          "light": "h-et-icon.svg",
          "dark": "h-et-icon-dark.svg"
        }
      ]
    },
    {
      "name": "I. Point of view (The user's eye)",
      "variants": [
        {
          "id": "I",
          "name": "Mark / favicon (lockups: index.html)",
          "description": "The user's eye. An eye drawn from two arcs whose pupil is a square: the product only exists as the user sees it. Sight first, object second. Favicon: the eye alone. Accent: Ink blue.",
          "light": "i-view-icon.svg",
          "dark": "i-view-icon-dark.svg"
        }
      ]
    },
    {
      "name": "J. Gauge (Data and evidence)",
      "variants": [
        {
          "id": "J",
          "name": "Mark / favicon (lockups: index.html)",
          "description": "Data and evidence. A heavy ruler with notches cut into it and one pointer on the reading: measured, not guessed. The site's claim is evidence from 15 years of practice. Favicon: the ruler and pointer. Accent: Ink blue.",
          "light": "j-gauge-icon.svg",
          "dark": "j-gauge-icon-dark.svg"
        }
      ]
    },
    {
      "name": "K. Keystone (Architecture)",
      "variants": [
        {
          "id": "K",
          "name": "Mark / favicon (lockups: index.html)",
          "description": "Architecture. An arch: two heavy sides, the user and the product, that only stand because one keystone at the top locks them together. That keystone is the site. Favicon: the arch and keystone. Accent: Ink blue.",
          "light": "k-keystone-icon.svg",
          "dark": "k-keystone-icon-dark.svg"
        }
      ]
    },
    {
      "name": "L. Ribbon (The printed page)",
      "variants": [
        {
          "id": "L",
          "name": "Mark / favicon (lockups: index.html)",
          "description": "The printed page. A heavy book block with a red ribbon marker: the page you keep and return to. The site as a reference work, not a feed. Favicon: the book and ribbon. Accent: Masthead red.",
          "light": "l-ribbon-icon.svg",
          "dark": "l-ribbon-icon-dark.svg"
        }
      ]
    }
  ]
};
